spring.application.name=auth-keycloak
spring.datasource.url=jdbc:mysql://localhost:3306/uberkeycloak
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database=mysql
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/myrealm
server.port=8094