apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
  KC_DB_USERNAME: keycloak

