apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: keycloakpass
  KC_DB_PASSWORD: keycloakpass
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: password

